export const PROVIDERS = {
  ollama: {
    name: "Ollama",
    icon: "🦙",
    color: "#34d399",
    needsKey: false,
    needsEndpoint: true,
    defaultEndpoint: "http://localhost:11434",
    canFetchModels: true,
    suggestedModels: [],
    hint: 'Start Ollama with: OLLAMA_ORIGINS="*" ollama serve — or enable CORS in your reverse proxy.',
    compat: "ollama",
    modelFilter: () => true,
  },
  openai: {
    name: "OpenAI",
    icon: "◆",
    color: "#74aa9c",
    needsKey: true,
    needsEndpoint: false,
    defaultEndpoint: "https://api.openai.com/v1",
    canFetchModels: true,
    suggestedModels: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"],
    hint: "OpenAI may block direct browser requests — use a local CORS proxy if needed.",
    compat: "openai",
    modelFilter: (id) =>
      id.startsWith("gpt-") || id.startsWith("o1") || id.startsWith("o3"),
  },
  groq: {
    name: "Groq",
    icon: "⚡",
    color: "#f59e0b",
    needsKey: true,
    needsEndpoint: false,
    defaultEndpoint: "https://api.groq.com/openai/v1",
    canFetchModels: true,
    suggestedModels: [
      "llama-3.3-70b-versatile",
      "llama-3.1-8b-instant",
      "mixtral-8x7b-32768",
    ],
    hint: null,
    compat: "openai",
    modelFilter: () => true,
  },
  anthropic: {
    name: "Anthropic",
    icon: "◈",
    color: "#a78bfa",
    needsKey: true,
    needsEndpoint: false,
    defaultEndpoint: "https://api.anthropic.com",
    canFetchModels: true,
    suggestedModels: [
      "claude-opus-4-6",
      "claude-sonnet-4-6",
      "claude-haiku-4-5-20251001",
    ],
    hint: null,
    compat: "anthropic",
    modelFilter: () => true,
  },
  google: {
    name: "Google",
    icon: "◎",
    color: "#4285f4",
    needsKey: true,
    needsEndpoint: false,
    defaultEndpoint: "https://generativelanguage.googleapis.com",
    canFetchModels: true,
    suggestedModels: ["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
    hint: null,
    compat: "google",
    modelFilter: (n) => n.includes("gemini"),
  },
  custom: {
    name: "Custom",
    icon: "⚙",
    color: "#94a3b8",
    needsKey: true,
    needsEndpoint: true,
    defaultEndpoint: "http://localhost:8000/v1",
    canFetchModels: false,
    suggestedModels: [],
    hint: "Any OpenAI-compatible endpoint — LiteLLM, LocalAI, vLLM, etc.",
    compat: "openai",
    modelFilter: () => true,
  },
};

export const ACCENT_COLORS = [
  "#a78bfa",
  "#fb923c",
  "#34d399",
  "#60a5fa",
  "#f59e0b",
  "#f472b6",
  "#22d3ee",
  "#a3e635",
];

export const ACCENT_ICONS = ["⚖", "✦", "⚡", "◈", "⚙", "◎", "❋", "◆"];
